exports.rouletteWheelNumbers = [
  0, 32, 15, 19, 4, 21, 2, 25, 17, 34, 6, 27, 13, 36, 11, 30, 8, 23, 10, 5, 24,
  16, 33, 1, 20, 14, 31, 9, 22, 18, 29, 7, 28, 12, 35, 3, 26,
];

exports.numberArray = [
  { no: 0, color: 'green', oddAndEven: 'even' },
  { no: 1, color: 'red', oddAndEven: 'odd' },
  { no: 2, color: 'black', oddAndEven: 'even' },
  { no: 3, color: 'red', oddAndEven: 'odd' },
  { no: 4, color: 'black', oddAndEven: 'even' },
  { no: 5, color: 'red', oddAndEven: 'odd' },
  { no: 6, color: 'black', oddAndEven: 'even' },
  { no: 7, color: 'red', oddAndEven: 'odd' },
  { no: 8, color: 'black', oddAndEven: 'even' },
  { no: 9, color: 'red', oddAndEven: 'odd' },
  { no: 10, color: 'black', oddAndEven: 'even' },
  { no: 11, color: 'black', oddAndEven: 'odd' },
  { no: 12, color: 'red', oddAndEven: 'even' },
  { no: 13, color: 'black', oddAndEven: 'odd' },
  { no: 14, color: 'red', oddAndEven: 'even' },
  { no: 15, color: 'black', oddAndEven: 'odd' },
  { no: 16, color: 'red', oddAndEven: 'even' },
  { no: 17, color: 'black', oddAndEven: 'odd' },
  { no: 18, color: 'red', oddAndEven: 'even' },
  { no: 19, color: 'red', oddAndEven: 'odd' },
  { no: 20, color: 'black', oddAndEven: 'even' },
  { no: 21, color: 'red', oddAndEven: 'odd' },
  { no: 22, color: 'black', oddAndEven: 'even' },
  { no: 23, color: 'red', oddAndEven: 'odd' },
  { no: 24, color: 'black', oddAndEven: 'even' },
  { no: 25, color: 'red', oddAndEven: 'odd' },
  { no: 26, color: 'black', oddAndEven: 'even' },
  { no: 27, color: 'red', oddAndEven: 'odd' },
  { no: 28, color: 'black', oddAndEven: 'even' },
  { no: 29, color: 'black', oddAndEven: 'odd' },
  { no: 30, color: 'red', oddAndEven: 'even' },
  { no: 31, color: 'black', oddAndEven: 'odd' },
  { no: 32, color: 'red', oddAndEven: 'even' },
  { no: 33, color: 'black', oddAndEven: 'odd' },
  { no: 34, color: 'red', oddAndEven: 'even' },
  { no: 35, color: 'black', oddAndEven: 'odd' },
  { no: 36, color: 'red', oddAndEven: 'even' },
];
